normal[:mod_php5_apache2][:packages] = [ 'php55-xml',
                                         'php55-common',
                                         'php55-xmlrpc',
                                         'php55-devel',
                                         'php55-gd',
                                         'php55-cli',
                                         'php55-pear-Auth-SASL',
                                         'php55-mysql',
                                         'php55-mcrypt',
                                         'php55-pecl-memcache',
                                         'php55-pear',
                                         'php55-pear-XML-Parser',
                                         'php55-pear-Mail-Mime',
                                         'php55-pear-DB',
                                         'php55-pear-HTML-Common']